# Generated by Django 2.2.5 on 2021-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('cardNumber', models.PositiveIntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfTicket', models.IntegerField(blank=True, default=0)),
                ('dateOfJourney', models.DateField(null=True)),
                ('bus_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(default='debit card', max_length=15)),
                ('refund_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('upi_id', models.CharField(max_length=45)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
