# Generated by Django 3.1.5 on 2021-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('cardNumber', models.PositiveIntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('upi_id', models.CharField(max_length=45)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bus_id',
            field=models.IntegerField(null='False'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateOfJourney',
            field=models.DateField(null='False'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numberOfTicket',
            field=models.IntegerField(null='False'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
