# Generated by Django 2.2.5 on 2021-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numberOfTicket',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
