# Generated by Django 2.2.5 on 2021-03-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20210307_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numberOfTicket',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
