# Generated by Django 2.2.5 on 2021-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20210307_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='numberoftickets',
            field=models.IntegerField(default=100),
        ),
    ]
