# Generated by Django 3.1.5 on 2021-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_promocode_numberoftickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
