# Generated by Django 3.1.5 on 2021-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_reservation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='r_id',
            field=models.IntegerField(null=True),
        ),
    ]
