# Generated by Django 2.2.5 on 2021-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('suggestions', models.TextField(blank=True)),
            ],
        ),
    ]
