# Generated by Django 2.2.5 on 2021-03-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
