# Generated by Django 3.1.5 on 2021-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busid', models.IntegerField(max_length=10)),
                ('busnumber', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
            ],
        ),
    ]
