# Generated by Django 3.1.5 on 2021-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='busid',
            field=models.IntegerField(),
        ),
    ]
