# Generated by Django 3.1.5 on 2021-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20210127_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.IntegerField(default=30),
        ),
    ]
