# Generated by Django 3.1.5 on 2021-01-27 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
