# Generated by Django 3.1.5 on 2021-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20210127_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='busid',
            new_name='bus_id',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='busnumber',
            new_name='bus_number',
        ),
    ]
