# Generated by Django 3.1.5 on 2021-01-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20210127_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
