# Generated by Django 3.1.5 on 2021-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_delete_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
