# Generated by Django 3.1.5 on 2021-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
    ]
