# Generated by Django 3.1.5 on 2021-01-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Db',
        ),
    ]
