# Generated by Django 3.1.5 on 2021-01-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_delete_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AddField(
            model_name='bus',
            name='pricePerSeat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
