# Generated by Django 3.1.5 on 2021-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_auto_20210131_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.IntegerField(null='False'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=10, null='False'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.IntegerField(default=30, null='False'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(max_length=10, null='False'),
        ),
    ]
