# Generated by Django 2.2.5 on 2021-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRecord',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=25, null=True)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
